{% set name = "jupyterlab_robotmode" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 860832398e1c3240ae69f346cdaee4f69c597413001070cc94becafb36d2809c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.6
    - pip
    - nodejs
    - jupyterlab =3
    - jupyter-packaging
  run:
    - python >=3.6

test:
  commands:
    - test -f ${PREFIX}/share/jupyter/labextensions/@marketsquare/jupyterlab_robotmode/package.json                        # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\@marketsquare/jupyterlab_robotmode\\package.json (exit 1)      # [win]

about:
  home: https://github.com/MarketSquare/jupyterlab_robotmode
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A JupyterLab extension which adds a CodeMirror mode for Robot Framework syntax'
  dev_url: https://github.com/MarketSquare/jupyterlab_robotmode

extra:
  recipe-maintainers:
    - martinRenou
